### ISSUE TITLE
Migrate to vector icon

### ISSUE THREAD

**Issue by Artem13327** [mueller-ma/Stopwatch#26]
Android 7 definitely already has support for vector icons, and I think it would be a good idea to switch to it, since this can reduce the weight of the application.
But I'm not an Android developer, so I don't know exactly how this affects Android's processing of the application.

**Comment by mueller-ma** [comment]
The app uses SVG icons except for the app icon on Android 7 and lower as adaptive icons were introduced in Android 8. Does this solve your issue?

**Comment by Artem13327** [comment]
Well, maybe I'm wrong, but did support for vector application icons appear before Android 8?

**Comment by mueller-ma** [comment]
Yes, but only for icons inside the app. All of them are SVG in Stopwatch.
